apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.backend.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
    {{- with .Values.backend }}
      - path: {{ .path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .name }}
            port:
              number: {{ .ports.port }}
    {{- end }}
